mysite_one/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('poll.urls')),
]

poll/urls.py
from django.conf.urls import url
from . import views

app_name = 'poll'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<poll_id>[0-9]+)/detail$', views.detail, name='detail'),
    url(r'^(?P<poll_id>[0-9]+)/vote$', views.vote, name='vote'),
    url(r'^(?P<poll_id>[0-9]+)/result$', views.result, name='result'),
]

poll/models.py
from django.db import models
from django.utils import timezone

class Poll(models.Model):
    auth = models.ForeignKey('auth.User', default=False)
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Date Published')

    def published(self):
        self.pub_date = timezone.now()
        self.save()

    def __str__(self):
        return self.question


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    vote = models.IntegerField(default=0)

poll/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, HttpResponse
from django.core.urlresolvers import reverse
from . models import Poll, Choice

def index(request):
    latest_poll_list = Poll.objects.all().order_by('-pub_date')[:6]
    return render(request, 'poll/index.html', {'latest_poll_list':latest_poll_list})

def detail(request, poll_id):
    poll = Poll.objects.get(pk=poll_id)
    return  render(request, 'poll/detail.html', {'poll':poll})

def vote(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = poll.choice_set.get(id=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'poll/detail.html', {
            'poll':poll,
            'error_message':"You didn't select a choice"
        })
    else:
        selected_choice.vote += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('poll:result', args=str(poll.id)))

def result(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    return render(request, 'poll/result.html', {
        'poll':poll
    })

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

{% include 'poll/head.html' %}

<body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden">
    <header class="app-header navbar">
        <button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">☰</button>
        <a class="navbar" href="{% url 'poll:index' %}"><strong style="font-size:20px; font-family: Lobster !important;">rk-world</strong></a>
        <button class="navbar-toggler sidebar-minimizer d-md-down-none" type="button">☰</button>

        <ul class="nav navbar-nav d-md-down-none">
            <li class="nav-item px-3">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item px-3">
                <a class="nav-link" href="#">Users</a>
            </li>
            <li class="nav-item px-3">
                <a class="nav-link" href="#">Settings</a>
            </li>
        </ul>
        <ul class="nav navbar-nav ml-auto">
            <li class="nav-item d-md-down-none">
                <a class="nav-link" href="#"><i class="icon-bell"></i><span class="badge badge-pill badge-danger">5</span></a>
            </li>
            <li class="nav-item d-md-down-none">
                <a class="nav-link" href="#"><i class="icon-list"></i></a>
            </li>
            <li class="nav-item d-md-down-none">
                <a class="nav-link" href="#"><i class="icon-location-pin"></i></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <img src="{% static 'img/avatars/55.jpg' %}" class="img-avatar" alt="rmsoft.com">
                    <span class="d-md-down-none">admin</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <div class="dropdown-header text-center">
                        <strong>Account</strong>
                    </div>
                    <a class="dropdown-item" href="#"><i class="fa fa-bell-o"></i> Updates<span class="badge badge-info">42</span></a>
                    <a class="dropdown-item" href="#"><i class="fa fa-envelope-o"></i> Messages<span class="badge badge-success">42</span></a>
                    <a class="dropdown-item" href="#"><i class="fa fa-tasks"></i> Tasks<span class="badge badge-danger">42</span></a>
                    <a class="dropdown-item" href="#"><i class="fa fa-comments"></i> Comments<span class="badge badge-warning">42</span></a>
                    <div class="dropdown-header text-center">
                        <strong>Settings</strong>
                    </div>
                    <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Profile</a>
                    <a class="dropdown-item" href="#"><i class="fa fa-wrench"></i> Settings</a>
                    <a class="dropdown-item" href="#"><i class="fa fa-usd"></i> Payments<span class="badge badge-default">42</span></a>
                    <a class="dropdown-item" href="#"><i class="fa fa-file"></i> Projects<span class="badge badge-primary">42</span></a>
                    <div class="divider"></div>
                    <a class="dropdown-item" href="#"><i class="fa fa-shield"></i> Lock Account</a>
                    <a class="dropdown-item" href="#"><i class="fa fa-lock"></i> Logout</a>
                </div>
            </li>
        </ul>
        <button class="navbar-toggler aside-menu-toggler" type="button">☰</button>

    </header>

    <div class="app-body">
        <div class="sidebar">
            <nav class="sidebar-nav">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i class="icon-speedometer"></i> Dashboard <span class="badge badge-primary">NEW</span></a>
                    </li>

                    <li class="nav-title">
                        Extras
                    </li>
                    <li class="nav-item nav-dropdown">
                        <a class="nav-link nav-dropdown-toggle" href="#"><i class="icon-star"></i> Pages</a>
                        <ul class="nav-dropdown-items">
                            <li class="nav-item">
                                <a class="nav-link" href="#" target="_top"><i class="icon-star"></i> Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#" target="_top"><i class="icon-star"></i> Register</a>
                            </li>
                        </ul>
                    </li>



                    <!--This is for poll list-->
                    {% block drop_poll_list %}

                    {% endblock %}



                </ul>
            </nav>
        </div>

        <!-- Main content -->
        <main class="main">

            <!-- Breadcrumb -->
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Home</li>
                <li class="breadcrumb-item"><a href="#">Admin</a>
                </li>
                <li class="breadcrumb-item active">Dashboard</li>

                <!-- Breadcrumb Menu-->
                <li class="breadcrumb-menu d-md-down-none">
                    <div class="btn-group" role="group" aria-label="Button group">
                        <a class="btn" href="#"><i class="icon-speech"></i></a>
                        <a class="btn" href="./"><i class="icon-graph"></i> &nbsp;Dashboard</a>
                        <a class="btn" href="#"><i class="icon-settings"></i> &nbsp;Settings</a>
                    </div>
                </li>
            </ol>


            <div class="container-fluid">


                <div class="animated fadeIn">
                    <div class="row">

                        <div class="col-md-12"></div>

                        <div class="col-md-8">

                            {% block content %}
                            {% endblock %}

                        </div>
                        <!--/.col-->

                        <div class="col-md-12"></div>

                    </div>
                    <!--/.row-->

                </div>

            </div>
            <!-- /.conainer-fluid -->
        </main>



        <aside class="aside-menu">
            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#timeline" role="tab"><i class="icon-list"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#messages" role="tab"><i class="icon-speech"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#settings" role="tab"><i class="icon-settings"></i></a>
                </li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane active" id="timeline" role="tabpanel">
                    <div class="callout m-0 py-2 text-muted text-center bg-light text-uppercase">
                        <small><b>Editing...</b>
                        </small>
                    </div>
                </div>
            </div>
        </aside>


    </div>

    {% include 'poll/footer.html' %}

    <!-- Bootstrap and necessary plugins -->
    {% include 'poll/extrafooter.html' %}

</body>

</html>

templates/detail.html
{% extends 'base.html' %}

{% block head_title %}Poll detail{% endblock %}

{% block content %}
<h1>{{ poll.question }}</h1>

<!--if anytime poll will not exist then this error_message will be show-->
{% if error_message %}
    {{ error_message }}
{% endif %}

<!--
If the choice of any poll is available, then this if block will be executed.
Otherwise the else block will be executed.
-->
{% if poll.choice_set.all %}

    <form action="{% url 'poll:vote' poll.id %}" method="post" class="formstyle">
        {% csrf_token %}
        {% for choice in poll.choice_set.all %}
            <input type="radio" id="choice{{ forloop.counter }}" name="choice" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">
                {{ choice.choice_text }}
            </label><br>
        {% endfor %}
        <input type="text">
        <div class="bottom">
            <input type="radio">
        </div>
        <input type="submit" value="Vote"/>
    </form>

{% else %}
    <p>There is no choice</p>
{% endif %}


<a href="{% url 'poll:index' %}"><i><strong>Back to home</strong></i></a>
{% endblock %}

templates/head.html
{% load staticfiles %}
<head>
    <meta charset="UTF-8">

    <!--CSS FILES-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/' %}"/>

    <!--JS FILES-->
    <script type="text/javascript" src="{% static 'js/' %}"></script>

</head>

templates/poll/detail.html
{% extends 'base.html' %}

{% block title %}Poll detail{% endblock %}

{% block content %}
<h1>{{ poll.question }}</h1>

<!--if anytime poll will not exist then this error_message will be show-->
{% if error_message %}
    {{ error_message }}
{% endif %}

<!--
If the choice of any poll is available, then this if block will be executed.
Otherwise the else block will be executed.
-->
{% if poll.choice_set.all %}

    <form action="{% url 'poll:vote' poll.id %}" method="post" class="formstyle">
        {% csrf_token %}
        {% for choice in poll.choice_set.all %}
            <input type="radio" id="choice{{ forloop.counter }}" name="choice" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">
                {{ choice.choice_text }}
            </label><br>
        {% endfor %}
        <input type="submit" value="Vote"/>
    </form>

{% else %}
    <p>There is no choice</p>
{% endif %}


<a href="{% url 'poll:index' %}"><i><strong>Back to home</strong></i></a>
{% endblock %}

templates/poll/extrafooter.html
{% load staticfiles %}

<!--This script will be replace at the end of body-->

<!-- Bootstrap and necessary plugins -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'bower_components/popper.js/index.js' %}"></script>
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'bower_components/pace/pace.min.js' %}"></script>


<!-- Plugins and scripts required by all views -->
<script src="{% static 'bower_components/chart.js/dist/Chart.min.js' %}"></script>


<!-- GenesisUI main scripts -->

<script src="{% static 'js/app.js' %}"></script>





<!-- Plugins and scripts required by this views -->

<!-- Custom scripts required by this view -->
<script src="{% static 'js/views/main.js' %}"></script>

templates/poll/footer.html
<!--This is for footer-->

<footer class="app-footer">
    <a href="#">rK</a> © 2017 rk-world.
    <span class="float-right">Powered by <a href="http://coreui.io">Md. Rubel Mahmud</a>
    </span>
</footer>

templates/poll/head.html
{% load staticfiles %}
<!--
<head>
    <meta charset="UTF-8">

    CSS FILES
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/'%}"/>

    <!--JS FILES--
    <script type="text/javascript" src="{% static 'js/' %}"></script>

</head>

-->


<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
    <meta name="author" content="Łukasz Holeczek">
    <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,AngularJS,Angular,Angular2,Angular 2,Angular4,Angular 4,jQuery,CSS,HTML,RWD,Dashboard,React,React.js,Vue,Vue.js">
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <title>rk-world</title>

    <!-- Icons -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/simple-line-icons.css' %}" rel="stylesheet">
    log/templates/blog/post_list.html
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">

    <!-- Main styles for this application -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

templates/poll/header.html
<!--This is for header, that will be extend's all of others html files included in this projects-->

<header class="app-header navbar">
        <button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">☰</button>
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler sidebar-minimizer d-md-down-none" type="button">☰</button>

        <ul class="nav navbar-nav d-md-down-none">
            <li class="nav-item px-3">
                <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item px-3">
                <a class="nav-link" href="#">Users</a>
            </li>
            <li class="nav-item px-3">
                <a class="nav-link" href="#">Settings</a>
            </li>
        </ul>
        <ul class="nav navbar-nav ml-auto">
            <li class="nav-item d-md-down-none">
                <a class="nav-link" href="#"><i class="icon-bell"></i><span class="badge badge-pill badge-danger">5</span></a>
            </li>
            <li class="nav-item d-md-down-none">
                <a class="nav-link" href="#"><i class="icon-list"></i></a>
            </li>
            <li class="nav-item d-md-down-none">
                <a class="nav-link" href="#"><i class="icon-location-pin"></i></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                    <img src="img/avatars/6.jpg" class="img-avatar" alt="admin@bootstrapmaster.com">
                    <span class="d-md-down-none">admin</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <div class="dropdown-header text-center">
                        <strong>Account</strong>
                    </div>
                    <a class="dropdown-item" href="#"><i class="fa fa-bell-o"></i> Updates<span class="badge badge-info">42</span></a>
                    <a class="dropdown-item" href="#"><i class="fa fa-envelope-o"></i> Messages<span class="badge badge-success">42</span></a>
                    <a class="dropdown-item" href="#"><i class="fa fa-tasks"></i> Tasks<span class="badge badge-danger">42</span></a>
                    <a class="dropdown-item" href="#"><i class="fa fa-comments"></i> Comments<span class="badge badge-warning">42</span></a>
                    <div class="dropdown-header text-center">
                        <strong>Settings</strong>
                    </div>
                    <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Profile</a>
                    <a class="dropdown-item" href="#"><i class="fa fa-wrench"></i> Settings</a>
                    <a class="dropdown-item" href="#"><i class="fa fa-usd"></i> Payments<span class="badge badge-default">42</span></a>
                    <a class="dropdown-item" href="#"><i class="fa fa-file"></i> Projects<span class="badge badge-primary">42</span></a>
                    <div class="divider"></div>
                    <a class="dropdown-item" href="#"><i class="fa fa-shield"></i> Lock Account</a>
                    <a class="dropdown-item" href="#"><i class="fa fa-lock"></i> Logout</a>
                </div>
            </li>
        </ul>
        <button class="navbar-toggler aside-menu-toggler" type="button">☰</button>
</header>

templates/poll/index.html
{% extends 'base.html' %}

{% block title %}Latest_poll_list{% endblock %}

{% block content %}

<h1>Here all of my Poll :</h1>
    {% if latest_poll_list %}
        <ul>
            {% for poll in latest_poll_list %}
                <li>
                    <strong><a href="{% url 'poll:detail' poll.id %}">{{ poll.question }}</a></strong>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No poll is available</p>
    {% endif %}

{% endblock content %}



{% block drop_poll_list %}
    <li class="nav-item nav-dropdown">
        <a class="nav-link nav-dropdown-toggle" href="#"><i class="icon-star"></i> Polls</a>

        {% if latest_poll_list %}
            <ul class="nav-dropdown-items">
                {% for poll in latest_poll_list %}
                    <li class="nav-item">
                        <a class="nav-link" href="#" target="_top"><i class="icon-star"></i>{{ poll.pub_date }}</a><br>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}

    </li>
{% endblock drop_poll_list %}

templates/poll/pre.html
<!-- 'base.html'

<!DOCTYPE html>

<html lang="en">
<head>

    <title>{% block title %}Poll_app{% endblock %}</title>

    {% include 'poll/head.html' %}

</head>
<body>



    {% block content %}
    {% endblock %}

    {% include 'poll/footer.html' %}

    {% include 'poll/extrafooter.html' %}

</body>
</html>

-->

templates/poll/result.html
{% extends 'base.html' %}

{% block title %}result of votes{% endblock %}

{% block content %}
<h1>{{ poll.question }}</h1>

{% for choice in poll.choice_set.all %}
    <p>"{{ choice.choice_text }}" get totall {{ choice.vote }} vote{{ choice.vote|pluralize }}</p>
{% endfor %}
<a href="{% url 'poll:detail' poll.id %}"><strong><i>Vote Again?</i></strong></a>
    <br>
    <br>
<a href="{% url 'poll:index' %}"><strong><i>Back to index page?</i></strong></a>
{% endblock %}

templates/result.html
{% extends 'base.html' %}

{% block head_title %}result of votes{% endblock %}

{% block content %}
<h1>{{ poll.question }}</h1>

{% for choice in poll.choice_set.all %}
    <p>"{{ choice.choice_text }}" get totall {{ choice.vote }} vote{{ choice.vote|pluralize }}</p>
{% endfor %}
<a href="{% url 'poll:detail' poll.id %}"><strong><i>Vote Again?</i></strong></a>
    <br>
    <br>
<a href="{% url 'poll:index' %}"><strong><i>Back to index page?</i></strong></a>
{% endblock %}